default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: rastreador
  password: <%= ENV["RASTREADOR_DATABASE_PASSWORD"] %>
  host: 127.0.0.1
  port: 3306

development:
  <<: *default
  database: rastreador_development

test:
  <<: *default
  database: rastreador_test

production:
  primary: &primary_production
    <<: *default
    database: rastreador_production
    username: rastreador
    password: <%= ENV["RASTREADOR_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rastreador_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rastreador_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rastreador_production_cable
    migrations_paths: db/cable_migrate
